server:
  port: 8080

spring:
  application:
    name: cloud-payment-consumer
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.halin.springcloud.entities
