server:
  port: 8802

spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders: # 配置要绑定的rabbitmq的服务信息
        defaultRabbit: # 表示定义的名称，用于binding整合
          type: rabbit # 消息组件类型
          environment: # 设置消息组件的环境配置
            spring:
              rabbitmq:
                host: 10.159.218.36
                port: 5672
                username: guest
                password: guest
      bindings: # 服务的整合处理
        input: # 这个名字是一个通道的名称
          destination: studyExchange # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型，本次为json，文本可以设置”text/plain“
          binder: defaultRabbit # 设置要绑定的消息服务的具体设置
          group: group1

eureka:
  instance-id: consumer-8802
  client:
    # 表示要将自己注册到eureka中
    register-with-eureka: true
    # 是否从eureka中住区已经有的注册信息，默认为true；
    # 单节点无所谓，集群必须设置为true才能配合
    fetch-registry: true
    service-url:
      # 配置集群需要同时添加多个eureka节点
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30s)，表示eureka client间隔多久去拉取服务注册信息
    lease-expiration-duration-in-seconds: 5 # 表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance（默认90s）