server:
  port: 8080

spring:
  application:
    name: cloud-payment-consumer

  cloud:
    consul:
      host: 10.159.218.36
      port: 8500
      discovery:
        service-name: ${spring.application.name}